CREATE TABLE ADDRESS (
  ID SERIAL PRIMARY KEY,
  STREET VARCHAR,
  NUMBER INT,
  CITY VARCHAR,
  STATE VARCHAR
);

CREATE TABLE CUSTOMERS (
  ID SERIAL PRIMARY KEY,
  FULL_NAME VARCHAR,
  CREATED_AT TIMESTAMP,
  CPF VARCHAR,
  ADDRESS_ID INT
);

CREATE TABLE MERCHANTS (
  ID SERIAL PRIMARY KEY,
  MERCHANT_NAME VARCHAR,
  CREATED_AT TIMESTAMP
);

CREATE TABLE ORDER_ITEMS (
  ORDER_ID INT,
  PRODUCT_ID INT,
  QUANTITY INT DEFAULT 1
);

CREATE TABLE ORDERS (
  ID SERIAL PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  STATUS VARCHAR,
  CREATED_AT DATE
);

CREATE TABLE PRODUCTS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR,
  MERCHANT_ID INT NOT NULL,
  PRICE REAL,
  STATUS VARCHAR,
  CREATED_AT TIMESTAMP
);

ALTER TABLE CUSTOMERS ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID);

ALTER TABLE ORDER_ITEMS ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID);

ALTER TABLE ORDER_ITEMS ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID);

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID);

ALTER TABLE PRODUCTS ADD FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS (ID);

CREATE INDEX PRODUCT_STATUS ON PRODUCTS (MERCHANT_ID, STATUS);

CREATE UNIQUE INDEX ON PRODUCTS (ID);

COMMENT ON COLUMN ORDERS.CREATED_AT IS 'WHEN ORDER CREATED';
